-- Seed del catálogo de nombres. GENERADO por scripts/generate-seed.mjs desde
-- src/data/names.ts — no editar a mano. Cuando el backend esté conectado,
-- Postgres es la fuente de verdad y el archivo local desaparece.

insert into public.names (slug, name, gender, origin, meaning) values
  ('emilia', 'Emilia', 'f', 'Latino', 'La que se esfuerza y no se rinde'),
  ('mateo', 'Mateo', 'm', 'Hebreo', 'Regalo de Dios'),
  ('violeta', 'Violeta', 'f', 'Latino', 'Como la flor'),
  ('leon', 'León', 'm', 'Latino', 'Valiente como el león'),
  ('noa', 'Noa', 'f', 'Hebreo', 'Movimiento, descanso'),
  ('isidora', 'Isidora', 'f', 'Griego', 'Regalo de la diosa Isis'),
  ('gaspar', 'Gaspar', 'm', 'Persa', 'El que guarda el tesoro'),
  ('maite', 'Maite', 'f', 'Vasco', 'Amada'),
  ('vicente', 'Vicente', 'm', 'Latino', 'El que vence'),
  ('amanda', 'Amanda', 'f', 'Latino', 'Digna de ser amada'),
  ('ariel', 'Ariel', 'x', 'Hebreo', 'León de Dios'),
  ('florencia', 'Florencia', 'f', 'Latino', 'La que florece'),
  ('clemente', 'Clemente', 'm', 'Latino', 'De carácter bondadoso'),
  ('antonia', 'Antonia', 'f', 'Latino', 'Valiosa, inestimable'),
  ('baltazar', 'Baltazar', 'm', 'Asirio', 'Protegido por Dios'),
  ('trinidad', 'Trinidad', 'f', 'Latino', 'Unión de tres en uno'),
  ('guadalupe', 'Guadalupe', 'f', 'Árabe', 'Río de amor escondido'),
  ('salvador', 'Salvador', 'm', 'Latino', 'El que salva'),
  ('julieta', 'Julieta', 'f', 'Latino', 'De raíces fuertes, juvenil'),
  ('maximiliano', 'Maximiliano', 'm', 'Latino', 'El más grande'),
  ('amparo', 'Amparo', 'f', 'Latino', 'La que protege y da refugio'),
  ('emiliano', 'Emiliano', 'm', 'Latino', 'El que trabaja con empeño'),
  ('cruz', 'Cruz', 'x', 'Latino', 'Símbolo de fe y encuentro'),
  ('rafaela', 'Rafaela', 'f', 'Hebreo', 'Sanada por Dios'),
  ('emma', 'Emma', 'f', 'Germánico', 'Universal, la que todo lo abarca'),
  ('sofia', 'Sofía', 'f', 'Griego', 'Sabiduría'),
  ('isabella', 'Isabella', 'f', 'Hebreo', 'Consagrada a Dios'),
  ('aurora', 'Aurora', 'f', 'Latino', 'Amanecer, la primera luz del día'),
  ('mia', 'Mía', 'f', 'Hebreo', 'Amada, deseada'),
  ('liam', 'Liam', 'm', 'Irlandés', 'Protector decidido'),
  ('lucas', 'Lucas', 'm', 'Latino', 'El que ilumina'),
  ('santiago', 'Santiago', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('facundo', 'Facundo', 'm', 'Latino', 'Elocuente, el que convence al hablar'),
  ('thiago', 'Thiago', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('benjamin', 'Benjamín', 'm', 'Hebreo', 'Hijo predilecto'),
  ('gael', 'Gael', 'm', 'Celta', 'Generoso, de espíritu libre'),
  ('maximo', 'Máximo', 'm', 'Latino', 'El más grande'),
  ('penelope', 'Penélope', 'f', 'Griego', 'La que teje su destino'),
  ('catalina', 'Catalina', 'f', 'Griego', 'Pura'),
  ('elena', 'Elena', 'f', 'Griego', 'Resplandeciente como antorcha'),
  ('irene', 'Irene', 'f', 'Griego', 'Paz'),
  ('zoe', 'Zoe', 'f', 'Griego', 'Vida'),
  ('melisa', 'Melisa', 'f', 'Griego', 'Abeja, dulce como la miel'),
  ('ofelia', 'Ofelia', 'f', 'Griego', 'La que ayuda'),
  ('alejandro', 'Alejandro', 'm', 'Griego', 'Protector de los hombres'),
  ('alejandra', 'Alejandra', 'f', 'Griego', 'Protectora de los hombres'),
  ('andres', 'Andrés', 'm', 'Griego', 'Valiente y fuerte'),
  ('nicolas', 'Nicolás', 'm', 'Griego', 'Victoria del pueblo'),
  ('sebastian', 'Sebastián', 'm', 'Griego', 'Digno de respeto, venerable'),
  ('teodoro', 'Teodoro', 'm', 'Griego', 'Regalo de Dios'),
  ('hector', 'Héctor', 'm', 'Griego', 'El que protege lo suyo'),
  ('damian', 'Damián', 'm', 'Griego', 'El que doma su espíritu'),
  ('agustina', 'Agustina', 'f', 'Latino', 'Majestuosa, digna de veneración'),
  ('josefa', 'Josefa', 'f', 'Hebreo', 'Dios añadirá'),
  ('martina', 'Martina', 'f', 'Latino', 'Guerrera, consagrada a Marte'),
  ('maria', 'María', 'f', 'Hebreo', 'Amada y excelsa'),
  ('antonella', 'Antonella', 'f', 'Latino', 'Pequeña y valiosa'),
  ('emily', 'Emily', 'f', 'Latino', 'La que se esfuerza'),
  ('valentina', 'Valentina', 'f', 'Latino', 'Valiente, llena de fuerza'),
  ('amelia', 'Amelia', 'f', 'Germánico', 'Trabajadora, enérgica'),
  ('renata', 'Renata', 'f', 'Latino', 'Renacida'),
  ('dominga', 'Dominga', 'f', 'Latino', 'Nacida en día del Señor'),
  ('luciana', 'Luciana', 'f', 'Latino', 'Nacida con la luz'),
  ('victoria', 'Victoria', 'f', 'Latino', 'La que triunfa'),
  ('samantha', 'Samantha', 'f', 'Arameo', 'La que escucha'),
  ('ignacia', 'Ignacia', 'f', 'Latino', 'De fuego interior'),
  ('leonor', 'Leonor', 'f', 'Occitano', 'Resplandor, luz propia'),
  ('amalia', 'Amalia', 'f', 'Germánico', 'Enérgica, emprendedora'),
  ('fernanda', 'Fernanda', 'f', 'Germánico', 'Valiente y audaz'),
  ('laura', 'Laura', 'f', 'Latino', 'Coronada de laureles, victoriosa'),
  ('colomba', 'Colomba', 'f', 'Latino', 'Paloma, símbolo de paz'),
  ('javiera', 'Javiera', 'f', 'Vasco', 'La de la casa nueva'),
  ('pascal', 'Pascal', 'f', 'Latino', 'Nacida en Pascua'),
  ('celeste', 'Celeste', 'f', 'Latino', 'Del cielo'),
  ('josefina', 'Josefina', 'f', 'Hebreo', 'Dios dará crecimiento'),
  ('lucia', 'Lucía', 'f', 'Latino', 'Portadora de luz'),
  ('matilda', 'Matilda', 'f', 'Germánico', 'Fuerte en la batalla'),
  ('olivia', 'Olivia', 'f', 'Latino', 'Olivo, símbolo de paz'),
  ('francisca', 'Francisca', 'f', 'Germánico', 'Libre, del pueblo franco'),
  ('alice', 'Alice', 'f', 'Germánico', 'De noble linaje'),
  ('magdalena', 'Magdalena', 'f', 'Hebreo', 'La de la torre'),
  ('camila', 'Camila', 'f', 'Latino', 'La que asiste en los ritos'),
  ('monserrat', 'Monserrat', 'f', 'Catalán', 'De la montaña sagrada'),
  ('matilde', 'Matilde', 'f', 'Germánico', 'Poderosa guerrera'),
  ('agustin', 'Agustín', 'm', 'Latino', 'Venerable, majestuoso'),
  ('tomas', 'Tomás', 'm', 'Arameo', 'Gemelo, compañero de vida'),
  ('joaquin', 'Joaquín', 'm', 'Hebreo', 'Dios lo hará fuerte'),
  ('martin', 'Martín', 'm', 'Latino', 'De espíritu guerrero'),
  ('matias', 'Matías', 'm', 'Hebreo', 'Don de Dios'),
  ('alonso', 'Alonso', 'm', 'Germánico', 'Noble y audaz'),
  ('luciano', 'Luciano', 'm', 'Latino', 'El que lleva la luz'),
  ('bruno', 'Bruno', 'm', 'Germánico', 'Fuerte y protector'),
  ('julian', 'Julián', 'm', 'Latino', 'De espíritu joven'),
  ('jose', 'José', 'm', 'Hebreo', 'Dios añadirá'),
  ('gabriel', 'Gabriel', 'm', 'Hebreo', 'Fuerza de Dios'),
  ('santino', 'Santino', 'm', 'Latino', 'Pequeño santo'),
  ('cristobal', 'Cristóbal', 'm', 'Griego', 'El que lleva a Cristo'),
  ('dante', 'Dante', 'm', 'Latino', 'Perseverante'),
  ('diego', 'Diego', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('juan', 'Juan', 'm', 'Hebreo', 'Dios es misericordioso'),
  ('simon', 'Simón', 'm', 'Hebreo', 'El que escucha'),
  ('ian', 'Ian', 'm', 'Escocés', 'Dios es compasivo'),
  ('amaro', 'Amaro', 'm', 'Latino', 'El que ama'),
  ('felipe', 'Felipe', 'm', 'Griego', 'Amigo de los caballos'),
  ('ignacio', 'Ignacio', 'm', 'Latino', 'Fuego que no se apaga'),
  ('noah', 'Noah', 'm', 'Hebreo', 'Descanso, consuelo'),
  ('pedro', 'Pedro', 'm', 'Griego', 'Piedra, roca firme'),
  ('rafael', 'Rafael', 'm', 'Hebreo', 'Sanado por Dios'),
  ('samuel', 'Samuel', 'm', 'Hebreo', 'Escuchado por Dios'),
  ('valentin', 'Valentín', 'm', 'Latino', 'Fuerte y valiente'),
  ('renato', 'Renato', 'm', 'Latino', 'Vuelto a nacer'),
  ('daniel', 'Daniel', 'm', 'Hebreo', 'Dios es mi juez'),
  ('bastian', 'Bastián', 'm', 'Griego', 'Digno de honra'),
  ('dylan', 'Dylan', 'm', 'Galés', 'Hijo del mar'),
  ('luis', 'Luis', 'm', 'Germánico', 'Guerrero ilustre'),
  ('valentino', 'Valentino', 'm', 'Latino', 'Lleno de valor'),
  ('franco', 'Franco', 'm', 'Germánico', 'Libre, del pueblo franco'),
  ('hugo', 'Hugo', 'm', 'Germánico', 'De mente y espíritu brillantes'),
  ('leo', 'Leo', 'm', 'Latino', 'De corazón de león'),
  ('manuel', 'Manuel', 'm', 'Hebreo', 'Dios con nosotros'),
  ('pablo', 'Pablo', 'm', 'Latino', 'Pequeño y humilde'),
  ('enzo', 'Enzo', 'm', 'Germánico', 'Señor de su hogar'),
  ('alvaro', 'Álvaro', 'm', 'Germánico', 'Defensor de todos'),
  ('luca', 'Luca', 'm', 'Latino', 'El que trae la luz'),
  ('gonzalo', 'Gonzalo', 'm', 'Germánico', 'Listo para la batalla'),
  ('mario', 'Mario', 'm', 'Latino', 'Consagrado a Marte'),
  ('adrian', 'Adrián', 'm', 'Latino', 'El que viene del mar'),
  ('oliver', 'Oliver', 'm', 'Latino', 'Como el olivo, portador de paz'),
  ('alex', 'Álex', 'm', 'Griego', 'Protector'),
  ('marcos', 'Marcos', 'm', 'Latino', 'El que defiende con fuerza'),
  ('david', 'David', 'm', 'Hebreo', 'El amado'),
  ('marco', 'Marco', 'm', 'Latino', 'De espíritu marcial'),
  ('antonio', 'Antonio', 'm', 'Latino', 'Valioso, inestimable'),
  ('miguel', 'Miguel', 'm', 'Hebreo', 'Quién como Dios'),
  ('javier', 'Javier', 'm', 'Vasco', 'De la casa nueva'),
  ('izan', 'Izan', 'm', 'Español', 'Firme y constante'),
  ('rodrigo', 'Rodrigo', 'm', 'Germánico', 'Famoso por su gloria'),
  ('marc', 'Marc', 'm', 'Catalán', 'De espíritu guerrero'),
  ('angel', 'Ángel', 'm', 'Griego', 'Mensajero'),
  ('carlos', 'Carlos', 'm', 'Germánico', 'Libre y fuerte'),
  ('dario', 'Darío', 'm', 'Persa', 'El que protege el bien'),
  ('adam', 'Adam', 'm', 'Hebreo', 'Hecho de tierra, el primero'),
  ('jaime', 'Jaime', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('nico', 'Nico', 'm', 'Griego', 'Victoria del pueblo'),
  ('pau', 'Pau', 'm', 'Catalán', 'Paz'),
  ('guillermo', 'Guillermo', 'm', 'Germánico', 'Protector decidido'),
  ('jorge', 'Jorge', 'm', 'Griego', 'El que trabaja la tierra'),
  ('eric', 'Eric', 'm', 'Nórdico', 'Gobernante eterno'),
  ('francisco', 'Francisco', 'm', 'Germánico', 'Libre, del pueblo franco'),
  ('amir', 'Amir', 'm', 'Árabe', 'Príncipe'),
  ('iker', 'Iker', 'm', 'Vasco', 'Portador de buenas noticias'),
  ('jesus', 'Jesús', 'm', 'Hebreo', 'Dios salva'),
  ('victor', 'Víctor', 'm', 'Latino', 'El vencedor'),
  ('sergio', 'Sergio', 'm', 'Latino', 'El guardián'),
  ('aaron', 'Aarón', 'm', 'Hebreo', 'Iluminado, el que guía'),
  ('mohamed', 'Mohamed', 'm', 'Árabe', 'Digno de alabanza'),
  ('julen', 'Julen', 'm', 'Vasco', 'De espíritu joven'),
  ('biel', 'Biel', 'm', 'Catalán', 'Fuerza de Dios'),
  ('unai', 'Unai', 'm', 'Vasco', 'Pastor'),
  ('nil', 'Nil', 'm', 'Catalán', 'Como el río Nilo'),
  ('saul', 'Saúl', 'm', 'Hebreo', 'El pedido a Dios'),
  ('marti', 'Martí', 'm', 'Catalán', 'De alma guerrera'),
  ('ares', 'Ares', 'x', 'Griego', 'Dios griego de la guerra'),
  ('isaac', 'Isaac', 'm', 'Hebreo', 'El que ríe'),
  ('ruben', 'Rubén', 'm', 'Hebreo', 'Mirad, un hijo'),
  ('ivan', 'Iván', 'm', 'Eslavo', 'Dios es misericordioso'),
  ('erik', 'Erik', 'm', 'Nórdico', 'Príncipe eterno'),
  ('alan', 'Alan', 'm', 'Celta', 'Armonioso, apuesto'),
  ('pol', 'Pol', 'm', 'Catalán', 'Pequeño y humilde'),
  ('aleix', 'Aleix', 'm', 'Catalán', 'Defensor'),
  ('fernando', 'Fernando', 'm', 'Germánico', 'Valiente y audaz'),
  ('rayan', 'Rayan', 'm', 'Árabe', 'Floreciente, puerta del paraíso'),
  ('jan', 'Jan', 'm', 'Catalán', 'Dios es misericordioso'),
  ('joel', 'Joel', 'm', 'Hebreo', 'Yahvé es su Dios'),
  ('alberto', 'Alberto', 'm', 'Germánico', 'De nobleza brillante'),
  ('arnau', 'Arnau', 'm', 'Catalán', 'Águila poderosa'),
  ('ander', 'Ander', 'm', 'Vasco', 'Valiente'),
  ('ismael', 'Ismael', 'm', 'Hebreo', 'Dios escucha'),
  ('luka', 'Luka', 'm', 'Eslavo', 'El que trae la luz'),
  ('fabio', 'Fabio', 'm', 'Latino', 'El que cultiva'),
  ('raul', 'Raúl', 'm', 'Germánico', 'Consejero valiente'),
  ('kai', 'Kai', 'm', 'Hawaiano', 'Mar'),
  ('neizan', 'Neizan', 'm', 'Español', 'Firme y singular'),
  ('aday', 'Aday', 'm', 'Guanche', 'Bajo el cielo'),
  ('aran', 'Aran', 'm', 'Catalán', 'Valle entre montañas'),
  ('elias', 'Elías', 'm', 'Hebreo', 'Mi Dios es Yahvé'),
  ('axel', 'Axel', 'm', 'Nórdico', 'Padre de la paz'),
  ('max', 'Max', 'm', 'Latino', 'El más grande'),
  ('vega', 'Vega', 'f', 'Español', 'Llanura fértil junto al río'),
  ('julia', 'Julia', 'f', 'Latino', 'Juvenil, de raíces fuertes'),
  ('paula', 'Paula', 'f', 'Latino', 'Pequeña y valiosa'),
  ('carmen', 'Carmen', 'f', 'Hebreo', 'Jardín de Dios'),
  ('alma', 'Alma', 'f', 'Latino', 'De alma noble'),
  ('carla', 'Carla', 'f', 'Germánico', 'Libre y fuerte'),
  ('lola', 'Lola', 'f', 'Español', 'La que consuela'),
  ('gala', 'Gala', 'f', 'Latino', 'Serena y elegante'),
  ('lara', 'Lara', 'f', 'Latino', 'Ninfa romana, madre de los Lares'),
  ('daniela', 'Daniela', 'f', 'Hebreo', 'Dios es mi juez'),
  ('sara', 'Sara', 'f', 'Hebreo', 'Princesa'),
  ('jimena', 'Jimena', 'f', 'Hebreo', 'La que escucha'),
  ('chloe', 'Chloe', 'f', 'Griego', 'Brote verde, primavera'),
  ('claudia', 'Claudia', 'f', 'Latino', 'De la familia romana Claudia'),
  ('alba', 'Alba', 'f', 'Latino', 'Amanecer'),
  ('laia', 'Laia', 'f', 'Catalán', 'La que habla con dulzura'),
  ('candela', 'Candela', 'f', 'Latino', 'Llama que ilumina'),
  ('manuela', 'Manuela', 'f', 'Hebreo', 'Dios con nosotros'),
  ('triana', 'Triana', 'f', 'Español', 'La del otro lado del río'),
  ('vera', 'Vera', 'f', 'Latino', 'Verdadera'),
  ('ana', 'Ana', 'f', 'Hebreo', 'Llena de gracia'),
  ('aitana', 'Aitana', 'f', 'Español', 'Montaña luminosa'),
  ('carlota', 'Carlota', 'f', 'Germánico', 'Libre y decidida'),
  ('blanca', 'Blanca', 'f', 'Germánico', 'Brillante y luminosa'),
  ('ines', 'Inés', 'f', 'Griego', 'Pura, sagrada'),
  ('adriana', 'Adriana', 'f', 'Latino', 'Venida del mar'),
  ('lia', 'Lía', 'f', 'Hebreo', 'La que une'),
  ('abril', 'Abril', 'f', 'Latino', 'La que florece en primavera'),
  ('nora', 'Nora', 'f', 'Árabe', 'Luz y honor'),
  ('clara', 'Clara', 'f', 'Latino', 'Luminosa y transparente'),
  ('marina', 'Marina', 'f', 'Latino', 'Del mar'),
  ('luna', 'Luna', 'f', 'Latino', 'Luz de la noche'),
  ('rocio', 'Rocío', 'f', 'Latino', 'Frescura del amanecer'),
  ('marta', 'Marta', 'f', 'Arameo', 'Señora'),
  ('amira', 'Amira', 'f', 'Árabe', 'Princesa'),
  ('alicia', 'Alicia', 'f', 'Germánico', 'De noble linaje'),
  ('celia', 'Celia', 'f', 'Latino', 'Del cielo'),
  ('gabriela', 'Gabriela', 'f', 'Hebreo', 'Fuerza de Dios'),
  ('eva', 'Eva', 'f', 'Hebreo', 'La que da vida'),
  ('leire', 'Leire', 'f', 'Vasco', 'Lugar sagrado'),
  ('ona', 'Ona', 'f', 'Catalán', 'Ola del mar'),
  ('india', 'India', 'f', 'Español', 'Tierra lejana del río Indo'),
  ('ariadna', 'Ariadna', 'f', 'Griego', 'La más pura, la que guía'),
  ('alaia', 'Alaia', 'f', 'Vasco', 'Alegre'),
  ('isabel', 'Isabel', 'f', 'Hebreo', 'Consagrada a Dios'),
  ('iria', 'Iria', 'f', 'Gallego', 'Tierra fértil'),
  ('iris', 'Iris', 'f', 'Griego', 'Arcoíris, mensajera del cielo'),
  ('angela', 'Ángela', 'f', 'Griego', 'Mensajera'),
  ('mar', 'Mar', 'f', 'Latino', 'Inmensa como el mar'),
  ('africa', 'África', 'f', 'Latino', 'Bañada por el sol'),
  ('aina', 'Aina', 'f', 'Catalán', 'Llena de gracia'),
  ('diana', 'Diana', 'f', 'Latino', 'Divina y luminosa'),
  ('cataleya', 'Cataleya', 'f', 'Español', 'Como la orquídea'),
  ('nour', 'Nour', 'f', 'Árabe', 'Luz'),
  ('lina', 'Lina', 'f', 'Árabe', 'Palmera joven, delicada'),
  ('adara', 'Adara', 'f', 'Árabe', 'Noble belleza'),
  ('ainara', 'Ainara', 'f', 'Vasco', 'Golondrina'),
  ('andrea', 'Andrea', 'x', 'Griego', 'Con la valentía por delante'),
  ('yasmin', 'Yasmin', 'f', 'Persa', 'Flor de jazmín'),
  ('aya', 'Aya', 'f', 'Árabe', 'Señal maravillosa'),
  ('ainhoa', 'Ainhoa', 'f', 'Vasco', 'Tierra fértil'),
  ('alana', 'Alana', 'f', 'Celta', 'Armoniosa'),
  ('macarena', 'Macarena', 'f', 'Griego', 'La que es feliz'),
  ('naia', 'Naia', 'f', 'Vasco', 'Ola, deseo'),
  ('jana', 'Jana', 'f', 'Hebreo', 'Dios es misericordioso'),
  ('elsa', 'Elsa', 'f', 'Hebreo', 'Consagrada a Dios'),
  ('layan', 'Layan', 'f', 'Árabe', 'Dulzura y suavidad'),
  ('aria', 'Aria', 'f', 'Italiano', 'Melodía, aire'),
  ('elia', 'Elia', 'x', 'Hebreo', 'Mi Dios es Yahvé'),
  ('helena', 'Helena', 'f', 'Griego', 'Antorcha resplandeciente'),
  ('maia', 'Maia', 'f', 'Griego', 'Madre, la que nutre'),
  ('aroa', 'Aroa', 'f', 'Vasco', 'Tiempo favorable'),
  ('leyre', 'Leyre', 'f', 'Vasco', 'Monte sagrado'),
  ('nerea', 'Nerea', 'f', 'Vasco', 'La del mar'),
  ('teresa', 'Teresa', 'f', 'Griego', 'Cosechadora de verano'),
  ('fatima', 'Fátima', 'f', 'Árabe', 'Única y resplandeciente'),
  ('valeria', 'Valeria', 'f', 'Latino', 'Fuerte y saludable'),
  ('leonardo', 'Leonardo', 'm', 'Germánico', 'Fuerte como un león'),
  ('edoardo', 'Edoardo', 'm', 'Germánico', 'Guardián de la riqueza'),
  ('tommaso', 'Tommaso', 'm', 'Arameo', 'Gemelo, compañero de vida'),
  ('francesco', 'Francesco', 'm', 'Germánico', 'Libre, del pueblo franco'),
  ('alessandro', 'Alessandro', 'm', 'Griego', 'Protector de los hombres'),
  ('mattia', 'Mattia', 'm', 'Hebreo', 'Don de Dios'),
  ('lorenzo', 'Lorenzo', 'm', 'Latino', 'Coronado de laureles'),
  ('gabriele', 'Gabriele', 'm', 'Hebreo', 'Fuerza de Dios'),
  ('riccardo', 'Riccardo', 'm', 'Germánico', 'Rey valiente'),
  ('giuseppe', 'Giuseppe', 'm', 'Hebreo', 'Dios añadirá'),
  ('matteo', 'Matteo', 'm', 'Hebreo', 'Regalo de Dios'),
  ('enea', 'Enea', 'x', 'Griego', 'Héroe de la Eneida; en vasco, mía'),
  ('nicolo', 'Nicolò', 'm', 'Griego', 'Victoria del pueblo'),
  ('federico', 'Federico', 'm', 'Germánico', 'Príncipe de la paz'),
  ('giovanni', 'Giovanni', 'm', 'Hebreo', 'Dios es misericordioso'),
  ('filippo', 'Filippo', 'm', 'Griego', 'Amigo de los caballos'),
  ('samuele', 'Samuele', 'm', 'Hebreo', 'Escuchado por Dios'),
  ('pietro', 'Pietro', 'm', 'Griego', 'Piedra, roca firme'),
  ('giulio', 'Giulio', 'm', 'Latino', 'Juvenil'),
  ('gioele', 'Gioele', 'm', 'Hebreo', 'Yahvé es su Dios'),
  ('davide', 'Davide', 'm', 'Hebreo', 'El amado'),
  ('michele', 'Michele', 'm', 'Hebreo', 'Quién como Dios'),
  ('christian', 'Christian', 'm', 'Latino', 'Seguidor de Cristo'),
  ('salvatore', 'Salvatore', 'm', 'Latino', 'El que salva'),
  ('vincenzo', 'Vincenzo', 'm', 'Latino', 'El que vence'),
  ('thomas', 'Thomas', 'm', 'Arameo', 'Gemelo'),
  ('emanuele', 'Emanuele', 'm', 'Hebreo', 'Dios con nosotros'),
  ('alessio', 'Alessio', 'm', 'Griego', 'Defensor'),
  ('nathan', 'Nathan', 'm', 'Hebreo', 'Dios ha dado'),
  ('giorgio', 'Giorgio', 'm', 'Griego', 'El que trabaja la tierra'),
  ('jacopo', 'Jacopo', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('giacomo', 'Giacomo', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('ettore', 'Ettore', 'm', 'Griego', 'El que protege lo suyo'),
  ('raffaele', 'Raffaele', 'm', 'Hebreo', 'Sanado por Dios'),
  ('daniele', 'Daniele', 'm', 'Hebreo', 'Dios es mi juez'),
  ('simone', 'Simone', 'x', 'Hebreo', 'Dios ha escuchado'),
  ('luigi', 'Luigi', 'm', 'Germánico', 'Guerrero ilustre'),
  ('damiano', 'Damiano', 'm', 'Griego', 'El que doma su espíritu'),
  ('domenico', 'Domenico', 'm', 'Latino', 'Consagrado al Señor'),
  ('ginevra', 'Ginevra', 'f', 'Celta', 'Blanca como la espuma del mar'),
  ('vittoria', 'Vittoria', 'f', 'Latino', 'La que triunfa'),
  ('giulia', 'Giulia', 'f', 'Latino', 'Juvenil'),
  ('beatrice', 'Beatrice', 'f', 'Latino', 'Bienaventurada'),
  ('ludovica', 'Ludovica', 'f', 'Germánico', 'Guerrera ilustre'),
  ('anna', 'Anna', 'f', 'Hebreo', 'Llena de gracia'),
  ('camilla', 'Camilla', 'f', 'Latino', 'La que asiste en los ritos'),
  ('bianca', 'Bianca', 'f', 'Germánico', 'Blanca, brillante'),
  ('azzurra', 'Azzurra', 'f', 'Italiano', 'Azul como el cielo'),
  ('chiara', 'Chiara', 'f', 'Latino', 'Clara y luminosa'),
  ('nicole', 'Nicole', 'f', 'Griego', 'Victoria del pueblo'),
  ('giorgia', 'Giorgia', 'f', 'Griego', 'La que trabaja la tierra'),
  ('greta', 'Greta', 'f', 'Griego', 'Perla'),
  ('noemi', 'Noemi', 'f', 'Hebreo', 'Dulzura'),
  ('arianna', 'Arianna', 'f', 'Griego', 'La más pura'),
  ('gaia', 'Gaia', 'f', 'Griego', 'Madre tierra'),
  ('rebecca', 'Rebecca', 'f', 'Hebreo', 'Lazo, la que une'),
  ('viola', 'Viola', 'f', 'Latino', 'Violeta, la flor'),
  ('ambra', 'Ambra', 'f', 'Árabe', 'Ámbar dorado'),
  ('adele', 'Adele', 'f', 'Germánico', 'De estirpe noble'),
  ('francesca', 'Francesca', 'f', 'Germánico', 'Libre, del pueblo franco'),
  ('margherita', 'Margherita', 'f', 'Griego', 'Perla'),
  ('sole', 'Sole', 'f', 'Italiano', 'Sol'),
  ('cecilia', 'Cecilia', 'f', 'Latino', 'De linaje romano, patrona de la música'),
  ('gioia', 'Gioia', 'f', 'Italiano', 'Alegría'),
  ('elisa', 'Elisa', 'f', 'Hebreo', 'Dios es abundancia'),
  ('nina', 'Nina', 'f', 'Italiano', 'Diminutivo; en quechua, fuego'),
  ('lavinia', 'Lavinia', 'f', 'Latino', 'Madre del pueblo romano'),
  ('anita', 'Anita', 'f', 'Hebreo', 'Compasiva y llena de gracia'),
  ('eleonora', 'Eleonora', 'f', 'Occitano', 'Resplandor, luz propia'),
  ('carlotta', 'Carlotta', 'f', 'Germánico', 'Libre y fuerte'),
  ('giada', 'Giada', 'f', 'Italiano', 'Piedra de jade'),
  ('jazmin', 'Jazmín', 'f', 'Persa', 'Flor de jazmín'),
  ('ambar', 'Ámbar', 'f', 'Árabe', 'Dorada como la resina del sol'),
  ('franchesca', 'Franchesca', 'f', 'Italiano', 'Libre, del pueblo franco'),
  ('delfina', 'Delfina', 'f', 'Griego', 'Como el delfín, juguetona'),
  ('luz', 'Luz', 'f', 'Latino', 'Claridad que guía'),
  ('abigail', 'Abigail', 'f', 'Hebreo', 'Alegría de su padre'),
  ('benicio', 'Benicio', 'm', 'Latino', 'Bendecido'),
  ('eithan', 'Eithan', 'm', 'Hebreo', 'Firme y perdurable'),
  ('lionel', 'Lionel', 'm', 'Francés', 'Joven león'),
  ('ezequiel', 'Ezequiel', 'm', 'Hebreo', 'Dios fortalece'),
  ('ximena', 'Ximena', 'f', 'Hebreo', 'La que sabe escuchar'),
  ('regina', 'Regina', 'f', 'Latino', 'Reina'),
  ('maria-jose', 'María José', 'f', 'Hebreo', 'Gracia y promesa de Dios'),
  ('maria-fernanda', 'María Fernanda', 'f', 'Hebreo', 'Amada y valiente'),
  ('alexander', 'Alexander', 'm', 'Griego', 'Protector de los hombres'),
  ('miguel-angel', 'Miguel Ángel', 'm', 'Hebreo', 'Guerrero y mensajero de Dios'),
  ('rayen', 'Rayén', 'f', 'Mapuche', 'Flor'),
  ('aylen', 'Aylén', 'f', 'Mapuche', 'Brasa'),
  ('millaray', 'Millaray', 'f', 'Mapuche', 'Flor de oro'),
  ('lautaro', 'Lautaro', 'm', 'Mapuche', 'Toqui mapuche del siglo XVI'),
  ('amaru', 'Amaru', 'm', 'Quechua', 'Gran serpiente mítica'),
  ('ayelen', 'Ayelén', 'f', 'Mapuche', 'Risueña, la que ríe'),
  ('nahuel', 'Nahuel', 'm', 'Mapuche', 'Jaguar'),
  ('eluney', 'Eluney', 'x', 'Mapuche', 'Regalo'),
  ('anahi', 'Anahí', 'f', 'Guaraní', 'Heroína de la leyenda del ceibo'),
  ('antu', 'Antü', 'x', 'Mapuche', 'Sol'),
  ('tahiel', 'Tahiel', 'm', 'Mapuche', 'Canto ceremonial'),
  ('inti', 'Inti', 'm', 'Quechua', 'Sol, divinidad inca'),
  ('aukan', 'Aukán', 'm', 'Mapuche', 'Rebelde, travieso'),
  ('nayra', 'Nayra', 'f', 'Aymara', 'Ojo; también, tiempo antiguo'),
  ('newen', 'Newen', 'm', 'Mapuche', 'Fuerza'),
  ('amancay', 'Amancay', 'f', 'Quechua', 'Azucena andina'),
  ('ayun', 'Ayün', 'x', 'Mapuche', 'Amor'),
  ('suyai', 'Suyai', 'f', 'Quechua', 'Esperanza'),
  ('aliwen', 'Aliwen', 'x', 'Mapuche', 'Árbol'),
  ('likan', 'Likán', 'm', 'Mapuche', 'Piedra preciada por las machis'),
  ('kallfu', 'Kallfü', 'x', 'Mapuche', 'Azul'),
  ('liwen', 'Liwen', 'x', 'Mapuche', 'La mañana'),
  ('kuyen', 'Kuyén', 'f', 'Mapuche', 'Luna'),
  ('munay', 'Munay', 'x', 'Quechua', 'Querer, amar'),
  ('maiten', 'Maitén', 'f', 'Mapuche', 'El árbol maitén'),
  ('relmu', 'Relmu', 'x', 'Mapuche', 'Arcoíris'),
  ('illari', 'Illari', 'f', 'Quechua', 'Amanecer'),
  ('llanka', 'Llanka', 'f', 'Mapuche', 'Cuenta de piedra verde'),
  ('yael', 'Yael', 'x', 'Hebreo', 'Íbice, cabra montés'),
  ('jael', 'Jael', 'x', 'Hebreo', 'Íbice, cabra montés'),
  ('ari', 'Ari', 'x', 'Hebreo', 'León'),
  ('eden', 'Eden', 'x', 'Hebreo', 'Paraíso'),
  ('sasha', 'Sasha', 'x', 'Ruso', 'Quien protege a los demás'),
  ('akira', 'Akira', 'x', 'Japonés', 'Luz, claridad'),
  ('morgan', 'Morgan', 'x', 'Galés', 'Del mar'),
  ('robin', 'Robin', 'x', 'Inglés', 'Fama brillante'),
  ('taylor', 'Taylor', 'x', 'Inglés', 'Sastre'),
  ('marley', 'Marley', 'x', 'Inglés', 'Del bosque'),
  ('quimey', 'Quimey', 'x', 'Mapuche', 'Lo bueno'),
  ('katari', 'Katari', 'x', 'Aymara', 'Serpiente'),
  ('altair', 'Altair', 'x', 'Árabe', 'Águila en vuelo'),
  ('lur', 'Lur', 'x', 'Vasco', 'Tierra'),
  ('haize', 'Haize', 'x', 'Vasco', 'Viento'),
  ('constanza', 'Constanza', 'f', 'Latino', 'Constancia, firmeza'),
  ('emilio', 'Emilio', 'm', 'Latino', 'El que se esfuerza'),
  ('belen', 'Belén', 'f', 'Hebreo', 'Casa del pan'),
  ('paz', 'Paz', 'f', 'Latino', 'Del latín pax, la paz'),
  ('cristian', 'Cristian', 'm', 'Latino', 'Seguidor de Cristo'),
  ('gustavo', 'Gustavo', 'm', 'Nórdico', 'Bastón de los godos'),
  ('esteban', 'Esteban', 'm', 'Griego', 'Corona, guirnalda'),
  ('pia', 'Pía', 'f', 'Latino', 'Piadosa, devota'),
  ('eduardo', 'Eduardo', 'm', 'Germánico', 'Guardián de la riqueza'),
  ('camilo', 'Camilo', 'm', 'Latino', 'El que asiste en los ritos'),
  ('fabian', 'Fabián', 'm', 'Latino', 'De la familia de Fabio'),
  ('mariana', 'Mariana', 'f', 'Latino', 'Devota de María'),
  ('elizabeth', 'Elizabeth', 'f', 'Hebreo', 'Dios es mi juramento'),
  ('cristopher', 'Cristopher', 'm', 'Griego', 'El que lleva a Cristo'),
  ('jean', 'Jean', 'm', 'Francés', 'Dios es misericordioso'),
  ('genesis', 'Génesis', 'f', 'Griego', 'Origen, nacimiento'),
  ('ricardo', 'Ricardo', 'm', 'Germánico', 'Rey valiente'),
  ('alexis', 'Alexis', 'm', 'Griego', 'Defensor'),
  ('oscar', 'Óscar', 'm', 'Irlandés', 'Amigo de los ciervos'),
  ('kevin', 'Kevin', 'm', 'Irlandés', 'Gentil de nacimiento'),
  ('claudio', 'Claudio', 'm', 'Latino', 'De la familia romana Claudia'),
  ('marcelo', 'Marcelo', 'm', 'Latino', 'Pequeño Marco, de Marte'),
  ('mauricio', 'Mauricio', 'm', 'Latino', 'De Mauritania'),
  ('denisse', 'Denisse', 'f', 'Francés', 'Consagrada a Dioniso'),
  ('patricio', 'Patricio', 'm', 'Latino', 'De familia noble'),
  ('barbara', 'Bárbara', 'f', 'Griego', 'Extranjera'),
  ('carolina', 'Carolina', 'f', 'Germánico', 'Libre y fuerte'),
  ('alexandra', 'Alexandra', 'f', 'Griego', 'Protectora de los demás'),
  ('cesar', 'César', 'm', 'Latino', 'Título de los emperadores romanos'),
  ('jonathan', 'Jonathan', 'm', 'Hebreo', 'Dios ha dado'),
  ('roberto', 'Roberto', 'm', 'Germánico', 'Fama brillante'),
  ('rosa', 'Rosa', 'f', 'Latino', 'Como la flor'),
  ('juana', 'Juana', 'f', 'Hebreo', 'Dios es misericordioso'),
  ('margarita', 'Margarita', 'f', 'Griego', 'Perla'),
  ('olga', 'Olga', 'f', 'Ruso', 'Sagrada, bendita'),
  ('gladys', 'Gladys', 'f', 'Galés', 'La de su tierra'),
  ('eliana', 'Eliana', 'f', 'Latino', 'Del sol'),
  ('sonia', 'Sonia', 'f', 'Ruso', 'Sabiduría'),
  ('norma', 'Norma', 'f', 'Italiano', 'Sacerdotisa de la ópera de Bellini'),
  ('irma', 'Irma', 'f', 'Germánico', 'Universal, completa'),
  ('luisa', 'Luisa', 'f', 'Germánico', 'Guerrera ilustre'),
  ('gloria', 'Gloria', 'f', 'Latino', 'Gloria, fama'),
  ('hilda', 'Hilda', 'f', 'Germánico', 'Batalla'),
  ('graciela', 'Graciela', 'f', 'Latino', 'Gracia'),
  ('berta', 'Berta', 'f', 'Germánico', 'Brillante, ilustre'),
  ('raquel', 'Raquel', 'f', 'Hebreo', 'Oveja'),
  ('yolanda', 'Yolanda', 'f', 'Latino', 'Como la violeta'),
  ('mercedes', 'Mercedes', 'f', 'Español', 'Gracias, por la Virgen de la Merced'),
  ('elba', 'Elba', 'f', 'Incierto', 'Como el río y la isla'),
  ('fresia', 'Fresia', 'f', 'Español', 'Esposa de Caupolicán en La Araucana'),
  ('nelly', 'Nelly', 'f', 'Inglés', 'Diminutivo inglés de Elena'),
  ('aida', 'Aída', 'f', 'Italiano', 'Princesa de la ópera de Verdi'),
  ('guillermina', 'Guillermina', 'f', 'Germánico', 'Protectora decidida'),
  ('ester', 'Ester', 'f', 'Persa', 'Estrella'),
  ('georgina', 'Georgina', 'f', 'Griego', 'La que trabaja la tierra'),
  ('lucila', 'Lucila', 'f', 'Latino', 'Pequeña luz'),
  ('elvira', 'Elvira', 'f', 'Germánico', 'Alegre y sincera'),
  ('eugenia', 'Eugenia', 'f', 'Griego', 'Bien nacida'),
  ('filomena', 'Filomena', 'f', 'Griego', 'Amada'),
  ('ernestina', 'Ernestina', 'f', 'Germánico', 'Firme, resuelta'),
  ('zoila', 'Zoila', 'f', 'Griego', 'Llena de vida'),
  ('zunilda', 'Zunilda', 'f', 'Germánico', 'De raíz germánica, como Hilda'),
  ('hortensia', 'Hortensia', 'f', 'Latino', 'Del jardín'),
  ('uberlinda', 'Uberlinda', 'f', 'Incierto', 'Clásico de las abuelas chilenas'),
  ('luzmira', 'Luzmira', 'f', 'Español', 'Lleva la luz en su nombre'),
  ('herminia', 'Herminia', 'f', 'Latino', 'De la familia romana Herminia'),
  ('leontina', 'Leontina', 'f', 'Latino', 'Como una leona'),
  ('petronila', 'Petronila', 'f', 'Latino', 'De la familia romana Petronia'),
  ('clementina', 'Clementina', 'f', 'Latino', 'Bondadosa, clemente'),
  ('zulema', 'Zulema', 'f', 'Árabe', 'Pacífica'),
  ('rita', 'Rita', 'f', 'Italiano', 'Perla'),
  ('rosalia', 'Rosalía', 'f', 'Latino', 'De las rosas'),
  ('flora', 'Flora', 'f', 'Latino', 'Flor; diosa de la primavera'),
  ('pascuala', 'Pascuala', 'f', 'Latino', 'Nacida en Pascua'),
  ('eloisa', 'Eloísa', 'f', 'Germánico', 'Sana e íntegra'),
  ('lorenza', 'Lorenza', 'f', 'Latino', 'Coronada de laureles'),
  ('cordelia', 'Cordelia', 'f', 'Inglés', 'La hija fiel del rey Lear'),
  ('patricia', 'Patricia', 'f', 'Latino', 'De familia noble'),
  ('julio', 'Julio', 'm', 'Latino', 'Juvenil'),
  ('ramon', 'Ramón', 'm', 'Germánico', 'El que protege con su consejo'),
  ('hernan', 'Hernán', 'm', 'Germánico', 'Valiente y audaz'),
  ('rene', 'René', 'm', 'Francés', 'Vuelto a nacer'),
  ('segundo', 'Segundo', 'm', 'Latino', 'El segundo hijo'),
  ('osvaldo', 'Osvaldo', 'm', 'Germánico', 'Poder divino'),
  ('humberto', 'Humberto', 'm', 'Germánico', 'Osezno brillante'),
  ('domingo', 'Domingo', 'm', 'Latino', 'Nacido en día del Señor'),
  ('orlando', 'Orlando', 'm', 'Italiano', 'Fama de su tierra'),
  ('ernesto', 'Ernesto', 'm', 'Germánico', 'Firme, resuelto'),
  ('alfredo', 'Alfredo', 'm', 'Germánico', 'Consejo de los elfos'),
  ('bernardo', 'Bernardo', 'm', 'Germánico', 'Fuerte como un oso'),
  ('armando', 'Armando', 'm', 'Germánico', 'Hombre del ejército'),
  ('rolando', 'Rolando', 'm', 'Germánico', 'Fama de su tierra'),
  ('eugenio', 'Eugenio', 'm', 'Griego', 'Bien nacido'),
  ('heriberto', 'Heriberto', 'm', 'Germánico', 'Guerrero brillante'),
  ('reinaldo', 'Reinaldo', 'm', 'Germánico', 'El que gobierna con su consejo'),
  ('rigoberto', 'Rigoberto', 'm', 'Germánico', 'Soberano brillante'),
  ('gilberto', 'Gilberto', 'm', 'Germánico', 'Promesa brillante'),
  ('dagoberto', 'Dagoberto', 'm', 'Germánico', 'Brillante como el día'),
  ('arnoldo', 'Arnoldo', 'm', 'Germánico', 'Poder del águila'),
  ('waldo', 'Waldo', 'm', 'Germánico', 'El que gobierna'),
  ('edmundo', 'Edmundo', 'm', 'Germánico', 'Protector de la riqueza'),
  ('augusto', 'Augusto', 'm', 'Latino', 'Venerable, majestuoso'),
  ('gregorio', 'Gregorio', 'm', 'Griego', 'Vigilante'),
  ('leopoldo', 'Leopoldo', 'm', 'Germánico', 'Valiente entre su gente'),
  ('aurelio', 'Aurelio', 'm', 'Latino', 'Dorado'),
  ('horacio', 'Horacio', 'm', 'Latino', 'Nombre del gran poeta latino'),
  ('pascual', 'Pascual', 'm', 'Latino', 'Nacido en Pascua'),
  ('nicanor', 'Nicanor', 'm', 'Griego', 'Hombre victorioso'),
  ('wenceslao', 'Wenceslao', 'm', 'Eslavo', 'Más gloria'),
  ('octavio', 'Octavio', 'm', 'Latino', 'El octavo hijo'),
  ('benito', 'Benito', 'm', 'Latino', 'Bendito'),
  ('enrique', 'Enrique', 'm', 'Germánico', 'Señor de su casa')
on conflict (slug) do nothing;
