-- Seed del catálogo de nombres. GENERADO por scripts/generate-seed.mjs desde
-- src/data/names.ts — no editar a mano. Cuando el backend esté conectado,
-- Postgres es la fuente de verdad y el archivo local desaparece.

insert into public.names (slug, name, gender, origin, meaning) values
  ('emilia', 'Emilia', 'f', 'Latino', 'La que se esfuerza y no se rinde'),
  ('mateo', 'Mateo', 'm', 'Hebreo', 'Regalo de Dios'),
  ('violeta', 'Violeta', 'f', 'Latino', 'Como la flor, símbolo de modestia'),
  ('leon', 'León', 'm', 'Latino', 'Valiente como el león'),
  ('noa', 'Noa', 'x', 'Hebreo', 'Movimiento, descanso'),
  ('isidora', 'Isidora', 'f', 'Griego', 'Regalo de la diosa Isis'),
  ('gaspar', 'Gaspar', 'm', 'Persa', 'El que guarda el tesoro'),
  ('maite', 'Maite', 'f', 'Vasco', 'Amada'),
  ('vicente', 'Vicente', 'm', 'Latino', 'El que vence'),
  ('amanda', 'Amanda', 'f', 'Latino', 'Digna de ser amada'),
  ('ariel', 'Ariel', 'x', 'Hebreo', 'León de Dios'),
  ('florencia', 'Florencia', 'f', 'Latino', 'La que florece'),
  ('clemente', 'Clemente', 'm', 'Latino', 'De carácter bondadoso'),
  ('antonia', 'Antonia', 'f', 'Latino', 'Valiosa, inestimable'),
  ('baltazar', 'Baltazar', 'm', 'Asirio', 'Protegido por Dios'),
  ('trinidad', 'Trinidad', 'x', 'Latino', 'Unión de tres en uno'),
  ('guadalupe', 'Guadalupe', 'x', 'Árabe', 'Río de amor escondido'),
  ('salvador', 'Salvador', 'm', 'Latino', 'El que salva'),
  ('julieta', 'Julieta', 'f', 'Latino', 'De raíces fuertes, juvenil'),
  ('maximiliano', 'Maximiliano', 'm', 'Latino', 'El más grande'),
  ('amparo', 'Amparo', 'f', 'Latino', 'La que protege y da refugio'),
  ('emiliano', 'Emiliano', 'm', 'Latino', 'El que trabaja con empeño'),
  ('cruz', 'Cruz', 'x', 'Latino', 'Símbolo de fe y encuentro'),
  ('rafaela', 'Rafaela', 'f', 'Hebreo', 'Sanada por Dios'),
  ('emma', 'Emma', 'f', 'Germánico', 'Universal, la que todo lo abarca'),
  ('sofia', 'Sofía', 'f', 'Griego', 'Sabiduría'),
  ('isabella', 'Isabella', 'f', 'Hebreo', 'Consagrada a Dios'),
  ('aurora', 'Aurora', 'f', 'Latino', 'Amanecer, la primera luz del día'),
  ('mia', 'Mía', 'f', 'Hebreo', 'Amada, deseada'),
  ('liam', 'Liam', 'm', 'Irlandés', 'Protector decidido'),
  ('lucas', 'Lucas', 'm', 'Latino', 'El que ilumina'),
  ('santiago', 'Santiago', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('facundo', 'Facundo', 'm', 'Latino', 'Elocuente, el que convence al hablar'),
  ('thiago', 'Thiago', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('benjamin', 'Benjamín', 'm', 'Hebreo', 'Hijo predilecto'),
  ('gael', 'Gael', 'm', 'Celta', 'Generoso, de espíritu libre'),
  ('maximo', 'Máximo', 'm', 'Latino', 'El más grande'),
  ('penelope', 'Penélope', 'f', 'Griego', 'La que teje su destino'),
  ('catalina', 'Catalina', 'f', 'Griego', 'Pura'),
  ('elena', 'Elena', 'f', 'Griego', 'Resplandeciente como antorcha'),
  ('irene', 'Irene', 'f', 'Griego', 'Paz'),
  ('zoe', 'Zoe', 'f', 'Griego', 'Vida'),
  ('melisa', 'Melisa', 'f', 'Griego', 'Abeja, dulce como la miel'),
  ('ofelia', 'Ofelia', 'f', 'Griego', 'La que ayuda'),
  ('alejandro', 'Alejandro', 'm', 'Griego', 'Protector de los hombres'),
  ('alejandra', 'Alejandra', 'f', 'Griego', 'Protectora de los hombres'),
  ('andres', 'Andrés', 'm', 'Griego', 'Valiente y fuerte'),
  ('nicolas', 'Nicolás', 'm', 'Griego', 'Victoria del pueblo'),
  ('sebastian', 'Sebastián', 'm', 'Griego', 'Digno de respeto, venerable'),
  ('teodoro', 'Teodoro', 'm', 'Griego', 'Regalo de Dios'),
  ('hector', 'Héctor', 'm', 'Griego', 'El que protege lo suyo'),
  ('damian', 'Damián', 'm', 'Griego', 'El que doma su espíritu'),
  ('agustina', 'Agustina', 'f', 'Latino', 'Majestuosa, digna de veneración'),
  ('josefa', 'Josefa', 'f', 'Hebreo', 'Dios añadirá'),
  ('martina', 'Martina', 'f', 'Latino', 'Guerrera, consagrada a Marte'),
  ('maria', 'María', 'f', 'Hebreo', 'Amada y excelsa'),
  ('antonella', 'Antonella', 'f', 'Latino', 'Pequeña y valiosa'),
  ('emily', 'Emily', 'f', 'Latino', 'La que se esfuerza'),
  ('valentina', 'Valentina', 'f', 'Latino', 'Valiente, llena de fuerza'),
  ('amelia', 'Amelia', 'f', 'Germánico', 'Trabajadora, enérgica'),
  ('renata', 'Renata', 'f', 'Latino', 'Renacida'),
  ('dominga', 'Dominga', 'f', 'Latino', 'Nacida en día del Señor'),
  ('luciana', 'Luciana', 'f', 'Latino', 'Nacida con la luz'),
  ('victoria', 'Victoria', 'f', 'Latino', 'La que triunfa'),
  ('samantha', 'Samantha', 'f', 'Arameo', 'La que escucha'),
  ('ignacia', 'Ignacia', 'f', 'Latino', 'De fuego interior'),
  ('leonor', 'Leonor', 'f', 'Occitano', 'Resplandor, luz propia'),
  ('amalia', 'Amalia', 'f', 'Germánico', 'Enérgica, emprendedora'),
  ('fernanda', 'Fernanda', 'f', 'Germánico', 'Valiente y audaz'),
  ('laura', 'Laura', 'f', 'Latino', 'Coronada de laureles, victoriosa'),
  ('colomba', 'Colomba', 'f', 'Latino', 'Paloma, símbolo de paz'),
  ('javiera', 'Javiera', 'f', 'Vasco', 'La de la casa nueva'),
  ('pascal', 'Pascal', 'f', 'Hebreo', 'Nacida en Pascua'),
  ('celeste', 'Celeste', 'f', 'Latino', 'Del cielo'),
  ('josefina', 'Josefina', 'f', 'Hebreo', 'Dios dará crecimiento'),
  ('lucia', 'Lucía', 'f', 'Latino', 'Portadora de luz'),
  ('matilda', 'Matilda', 'f', 'Germánico', 'Fuerte en la batalla'),
  ('olivia', 'Olivia', 'f', 'Latino', 'Olivo, símbolo de paz'),
  ('francisca', 'Francisca', 'f', 'Germánico', 'Mujer libre'),
  ('alice', 'Alice', 'f', 'Germánico', 'De noble linaje'),
  ('magdalena', 'Magdalena', 'f', 'Hebreo', 'La de la torre'),
  ('camila', 'Camila', 'f', 'Latino', 'La que sirve con nobleza'),
  ('monserrat', 'Monserrat', 'f', 'Catalán', 'De la montaña sagrada'),
  ('matilde', 'Matilde', 'f', 'Germánico', 'Poderosa guerrera'),
  ('agustin', 'Agustín', 'm', 'Latino', 'Venerable, majestuoso'),
  ('tomas', 'Tomás', 'm', 'Arameo', 'Gemelo, compañero de vida'),
  ('joaquin', 'Joaquín', 'm', 'Hebreo', 'Dios lo hará fuerte'),
  ('martin', 'Martín', 'm', 'Latino', 'De espíritu guerrero'),
  ('matias', 'Matías', 'm', 'Hebreo', 'Don de Dios'),
  ('alonso', 'Alonso', 'm', 'Germánico', 'Noble y audaz'),
  ('luciano', 'Luciano', 'm', 'Latino', 'El que lleva la luz'),
  ('bruno', 'Bruno', 'm', 'Germánico', 'Fuerte y protector'),
  ('julian', 'Julián', 'm', 'Latino', 'De espíritu joven'),
  ('jose', 'José', 'm', 'Hebreo', 'Dios añadirá'),
  ('gabriel', 'Gabriel', 'm', 'Hebreo', 'Fuerza de Dios'),
  ('santino', 'Santino', 'm', 'Latino', 'Pequeño santo'),
  ('cristobal', 'Cristóbal', 'm', 'Griego', 'El que lleva a Cristo'),
  ('dante', 'Dante', 'm', 'Latino', 'Perseverante'),
  ('diego', 'Diego', 'm', 'Hebreo', 'Sostenido por Dios'),
  ('juan', 'Juan', 'm', 'Hebreo', 'Dios es misericordioso'),
  ('simon', 'Simón', 'm', 'Hebreo', 'El que escucha'),
  ('ian', 'Ian', 'm', 'Escocés', 'Dios es compasivo'),
  ('amaro', 'Amaro', 'm', 'Latino', 'El que ama'),
  ('felipe', 'Felipe', 'm', 'Griego', 'Amigo de los caballos'),
  ('ignacio', 'Ignacio', 'm', 'Latino', 'Fuego que no se apaga'),
  ('noah', 'Noah', 'm', 'Hebreo', 'Descanso, consuelo'),
  ('pedro', 'Pedro', 'm', 'Griego', 'Piedra, roca firme'),
  ('rafael', 'Rafael', 'm', 'Hebreo', 'Sanado por Dios'),
  ('samuel', 'Samuel', 'm', 'Hebreo', 'Escuchado por Dios'),
  ('valentin', 'Valentín', 'm', 'Latino', 'Fuerte y valiente'),
  ('renato', 'Renato', 'm', 'Latino', 'Vuelto a nacer'),
  ('daniel', 'Daniel', 'm', 'Hebreo', 'Dios es mi juez'),
  ('bastian', 'Bastián', 'm', 'Griego', 'Digno de honra'),
  ('dylan', 'Dylan', 'm', 'Galés', 'Hijo del mar'),
  ('luis', 'Luis', 'm', 'Germánico', 'Guerrero ilustre'),
  ('valentino', 'Valentino', 'm', 'Latino', 'Lleno de valor'),
  ('franco', 'Franco', 'm', 'Germánico', 'Hombre libre')
on conflict (slug) do nothing;
